/**
 * Global shared types for the Beacon platform.
 * All types are strictly inferred from Zod schemas in validation.ts.
 */

import {
  UserProfile,
  UserAdminMeta,
  TaskType as Task,
  NoteType as Note,
  SkillType as BaseSkill,
  UserSkillType as UserSkill,
  CareerPathType as CareerPath,
  CareerPathSkillType,
  ExtendedCareerPathSkill,
  ResourceTypeData as Resource,
  FeedbackType as SupportMessage,
  RecommendationType as Recommendation,
  CategoryType as Category,
  PlatformSettingsPublic,
  Stats,
  SeedMeta,
  AnnouncementType as Announcement,
  DifficultyLevel,
  ImportanceLevel,
  MinimumProficiencyLevel,
  ResourceType,
  SourceType,
  SkillProficiency,
} from "./validation";

// Re-export all validated types
export type {
  UserProfile,
  UserAdminMeta,
  Task,
  Note,
  BaseSkill,
  UserSkill,
  CareerPath,
  CareerPathSkillType,
  ExtendedCareerPathSkill,
  Resource,
  SupportMessage,
  Recommendation,
  Category,
  PlatformSettingsPublic,
  Stats,
  SeedMeta,
  Announcement,
  DifficultyLevel,
  ImportanceLevel,
  MinimumProficiencyLevel,
  ResourceType,
  SourceType,
  SkillProficiency,
};

// Backwards-compatible alias (some features still use this name)
export type CareerResource = Resource;

// ─────────────────────────────────────────────
// UI-only Helper Types (not stored in DB)
// ─────────────────────────────────────────────
export type AppRole = "admin" | "student";

export interface Skill extends BaseSkill {
  progress?: number;
}

export type NotificationType = "success" | "info" | "warning" | "error";

export interface AppNotification {
  id: string;
  title: string;
  message: string;
  type: NotificationType;
  read: boolean;
  createdAt: string;
}

export interface RadarDataPoint {
  category: string;
  score: number;
  fullMark: number;
}

// Career Opportunity — generated by AI, not stored as a DB collection
export interface CareerOpportunity {
  id: string;
  title: string;
  company: string;
  description?: string;
  location?: string;
  type?: string;
  sourceUrl: string;
  applicationUrl?: string;
  isVerified: boolean;
  verifiedAt?: string;
  generatedByAI: boolean;
  disclaimer?: string;
  relatedCareerPathId?: string;
  relatedSkillIds?: string[];
  createdAt?: string;
  updatedAt?: string;
  // UI Helpers (for AI responses)
  matchPercentage?: number;
  missingSkills?: string[];
}
