export const seedData = {
  categories: [
    { id: "cat_se", name: "Software Engineering", description: "Design, develop, and maintain software systems and applications.", icon: "Code" },
    { id: "cat_ds", name: "Data Science & Analytics", description: "Extract insights from data using statistical methods and programming.", icon: "Database" },
    { id: "cat_ai", name: "Artificial Intelligence", description: "Build intelligent systems using machine learning and deep learning.", icon: "Cpu" },
    { id: "cat_cloud", name: "Cloud & DevOps", description: "Design, deploy, and manage scalable cloud infrastructure.", icon: "Cloud" },
    { id: "cat_sec", name: "Cybersecurity", description: "Protect systems, networks, and programs from digital attacks.", icon: "Shield" },
    { id: "cat_design", name: "Design & UX/UI", description: "Create intuitive and aesthetically pleasing user experiences.", icon: "PenTool" },
    { id: "cat_pm", name: "Product Management", description: "Guide the strategy, development, and launch of products.", icon: "Briefcase" },
    { id: "cat_marketing", name: "Digital Marketing", description: "Promote products and brands using digital channels.", icon: "Megaphone" },
    { id: "cat_it", name: "IT Operations", description: "Manage and support an organization's IT infrastructure.", icon: "Server" },
    { id: "cat_mobile", name: "Mobile Development", description: "Develop applications for iOS and Android devices.", icon: "Smartphone" }
  ],
  paths: [
    { id: "path_fe", categoryId: "cat_se", title: "Frontend Developer", description: "Build the user interface and user experience of websites.", demandLevel: "High", requiredEducation: "Bachelor's Degree or Bootcamp" },
    { id: "path_be", categoryId: "cat_se", title: "Backend Developer", description: "Build the server-side logic and databases of web applications.", demandLevel: "High", requiredEducation: "Bachelor's Degree" },
    { id: "path_fs", categoryId: "cat_se", title: "Full Stack Developer", description: "Handle both frontend and backend development tasks.", demandLevel: "Very High", requiredEducation: "Bachelor's Degree" },
    { id: "path_da", categoryId: "cat_ds", title: "Data Analyst", description: "Analyze data sets to find trends and solve business problems.", demandLevel: "High", requiredEducation: "Bachelor's Degree" },
    { id: "path_de", categoryId: "cat_ds", title: "Data Engineer", description: "Design and build systems for collecting and analyzing data.", demandLevel: "Very High", requiredEducation: "Bachelor's Degree" },
    { id: "path_ds", categoryId: "cat_ds", title: "Data Scientist", description: "Use statistical methods to analyze complex data sets.", demandLevel: "High", requiredEducation: "Master's Degree" },
    { id: "path_mle", categoryId: "cat_ai", title: "Machine Learning Engineer", description: "Design and deploy machine learning models to production.", demandLevel: "Very High", requiredEducation: "Master's Degree" },
    { id: "path_cv", categoryId: "cat_ai", title: "Computer Vision Engineer", description: "Develop algorithms for processing and analyzing visual data.", demandLevel: "Medium", requiredEducation: "Master's Degree or PhD" },
    { id: "path_ca", categoryId: "cat_cloud", title: "Cloud Architect", description: "Design and oversee an organization's cloud computing strategy.", demandLevel: "High", requiredEducation: "Bachelor's Degree + Certifications" },
    { id: "path_do", categoryId: "cat_cloud", title: "DevOps Engineer", description: "Bridge the gap between software development and IT operations.", demandLevel: "Very High", requiredEducation: "Bachelor's Degree" },
    { id: "path_sec_analyst", categoryId: "cat_sec", title: "Security Analyst", description: "Monitor networks for security breaches and investigate violations.", demandLevel: "High", requiredEducation: "Bachelor's Degree" },
    { id: "path_pt", categoryId: "cat_sec", title: "Penetration Tester", description: "Simulate cyber attacks to identify vulnerabilities.", demandLevel: "Medium", requiredEducation: "Bachelor's Degree + Certifications" },
    { id: "path_ux", categoryId: "cat_design", title: "UX Designer", description: "Research and design the overall experience of a product.", demandLevel: "High", requiredEducation: "Bachelor's Degree or Portfolio" },
    { id: "path_ui", categoryId: "cat_design", title: "UI Designer", description: "Design the visual elements of a product's interface.", demandLevel: "High", requiredEducation: "Bachelor's Degree or Portfolio" },
    { id: "path_pm", categoryId: "cat_pm", title: "Product Manager", description: "Lead the development and strategy of a specific product.", demandLevel: "High", requiredEducation: "Bachelor's Degree" },
    { id: "path_po", categoryId: "cat_pm", title: "Product Owner", description: "Maximize the value of the product created by the scrum development team.", demandLevel: "Medium", requiredEducation: "Bachelor's Degree" },
    { id: "path_seo", categoryId: "cat_marketing", title: "SEO Specialist", description: "Optimize websites to rank higher in search engine results.", demandLevel: "High", requiredEducation: "Bachelor's Degree" },
    { id: "path_growth", categoryId: "cat_marketing", title: "Growth Hacker", description: "Use creative, low-cost strategies to acquire and retain customers.", demandLevel: "Medium", requiredEducation: "Bachelor's Degree" },
    { id: "path_sysadmin", categoryId: "cat_it", title: "System Administrator", description: "Maintain and operate computer systems and networks.", demandLevel: "Medium", requiredEducation: "Bachelor's Degree or Certifications" },
    { id: "path_ios", categoryId: "cat_mobile", title: "iOS Developer", description: "Develop mobile applications for Apple's iOS platform.", demandLevel: "High", requiredEducation: "Bachelor's Degree" },
    { id: "path_android", categoryId: "cat_mobile", title: "Android Developer", description: "Develop mobile applications for the Android platform.", demandLevel: "High", requiredEducation: "Bachelor's Degree" }
  ],
  skills: [
    { id: "skill_html", name: "HTML/CSS", description: "Fundamental technologies for building web pages." },
    { id: "skill_js", name: "JavaScript", description: "Programming language for web interactivity." },
    { id: "skill_ts", name: "TypeScript", description: "Typed superset of JavaScript." },
    { id: "skill_react", name: "React", description: "JavaScript library for building user interfaces." },
    { id: "skill_vue", name: "Vue.js", description: "Progressive JavaScript framework." },
    { id: "skill_node", name: "Node.js", description: "JavaScript runtime built on Chrome's V8 engine." },
    { id: "skill_python", name: "Python", description: "Versatile programming language widely used in AI/Data." },
    { id: "skill_java", name: "Java", description: "Object-oriented programming language." },
    { id: "skill_sql", name: "SQL", description: "Language for managing relational databases." },
    { id: "skill_nosql", name: "NoSQL", description: "Non-relational database management (e.g., MongoDB)." },
    { id: "skill_docker", name: "Docker", description: "Platform for developing, shipping, and running applications in containers." },
    { id: "skill_k8s", name: "Kubernetes", description: "System for automating deployment, scaling, and management of containerized applications." },
    { id: "skill_aws", name: "AWS", description: "Amazon Web Services cloud platform." },
    { id: "skill_azure", name: "Microsoft Azure", description: "Microsoft's cloud computing service." },
    { id: "skill_gcp", name: "Google Cloud Platform", description: "Google's suite of cloud computing services." },
    { id: "skill_git", name: "Git", description: "Version control system." },
    { id: "skill_agile", name: "Agile/Scrum", description: "Project management methodologies." },
    { id: "skill_figma", name: "Figma", description: "Collaborative interface design tool." },
    { id: "skill_pandas", name: "Pandas", description: "Data manipulation and analysis library for Python." },
    { id: "skill_tf", name: "TensorFlow", description: "End-to-end open source machine learning platform." },
    { id: "skill_pytorch", name: "PyTorch", description: "Open source machine learning framework." },
    { id: "skill_linux", name: "Linux", description: "Open-source operating system." },
    { id: "skill_bash", name: "Bash Scripting", description: "Command-line interface scripting." },
    { id: "skill_network", name: "Networking", description: "Understanding of computer networks and protocols." },
    { id: "skill_swift", name: "Swift", description: "Programming language for iOS." },
    { id: "skill_kotlin", name: "Kotlin", description: "Programming language for Android." },
    { id: "skill_seo", name: "SEO Optimization", description: "Search Engine Optimization techniques." },
    { id: "skill_ga", name: "Google Analytics", description: "Web analytics service." }
  ],
  pathSkills: [
    { pathId: "path_fe", skillIds: ["skill_html", "skill_js", "skill_ts", "skill_react", "skill_vue", "skill_git", "skill_figma"] },
    { pathId: "path_be", skillIds: ["skill_node", "skill_python", "skill_java", "skill_sql", "skill_nosql", "skill_docker", "skill_git", "skill_linux"] },
    { pathId: "path_fs", skillIds: ["skill_html", "skill_js", "skill_ts", "skill_react", "skill_node", "skill_sql", "skill_git"] },
    { pathId: "path_da", skillIds: ["skill_sql", "skill_python", "skill_pandas", "skill_ga"] },
    { pathId: "path_de", skillIds: ["skill_python", "skill_sql", "skill_nosql", "skill_aws", "skill_docker"] },
    { pathId: "path_ds", skillIds: ["skill_python", "skill_sql", "skill_pandas", "skill_tf", "skill_pytorch"] },
    { pathId: "path_mle", skillIds: ["skill_python", "skill_tf", "skill_pytorch", "skill_docker", "skill_aws", "skill_k8s"] },
    { pathId: "path_do", skillIds: ["skill_linux", "skill_bash", "skill_docker", "skill_k8s", "skill_aws", "skill_git"] },
    { pathId: "path_ca", skillIds: ["skill_aws", "skill_azure", "skill_gcp", "skill_network", "skill_linux"] },
    { pathId: "path_sec_analyst", skillIds: ["skill_network", "skill_linux", "skill_bash", "skill_python"] },
    { pathId: "path_ux", skillIds: ["skill_figma", "skill_html", "skill_agile"] },
    { pathId: "path_pm", skillIds: ["skill_agile", "skill_ga"] },
    { pathId: "path_ios", skillIds: ["skill_swift", "skill_git"] },
    { pathId: "path_android", skillIds: ["skill_kotlin", "skill_java", "skill_git"] }
  ],
  resources: [
    { title: "MDN Web Docs", url: "https://developer.mozilla.org/", resourceType: "Document", level: "All Levels", skillId: "skill_html" },
    { title: "JavaScript.info", url: "https://javascript.info/", resourceType: "Course", level: "All Levels", skillId: "skill_js" },
    { title: "React Official Documentation", url: "https://react.dev/", resourceType: "Document", level: "All Levels", skillId: "skill_react" },
    { title: "TypeScript Handbook", url: "https://www.typescriptlang.org/docs/", resourceType: "Document", level: "Intermediate", skillId: "skill_ts" },
    { title: "Node.js Design Patterns", url: "https://www.nodejsdesignpatterns.com/", resourceType: "Book", level: "Advanced", skillId: "skill_node" },
    { title: "Automate the Boring Stuff with Python", url: "https://automatetheboringstuff.com/", resourceType: "Book", level: "Beginner", skillId: "skill_python" },
    { title: "SQLBolt - Learn SQL", url: "https://sqlbolt.com/", resourceType: "Practice", level: "Beginner", skillId: "skill_sql" },
    { title: "Docker Curriculum", url: "https://docker-curriculum.com/", resourceType: "Course", level: "Intermediate", skillId: "skill_docker" },
    { title: "Kubernetes Basics", url: "https://kubernetes.io/docs/tutorials/kubernetes-basics/", resourceType: "Course", level: "Intermediate", skillId: "skill_k8s" },
    { title: "AWS Skill Builder", url: "https://skillbuilder.aws/", resourceType: "Course", level: "All Levels", skillId: "skill_aws" },
    { title: "Pro Git Book", url: "https://git-scm.com/book/en/v2", resourceType: "Book", level: "All Levels", skillId: "skill_git" },
    { title: "Figma Crash Course", url: "https://www.youtube.com/watch?v=jwKmJVyXzB0", resourceType: "Video", level: "Beginner", skillId: "skill_figma" },
    { title: "Pandas Documentation", url: "https://pandas.pydata.org/docs/", resourceType: "Document", level: "Intermediate", skillId: "skill_pandas" },
    { title: "TensorFlow Tutorials", url: "https://www.tensorflow.org/tutorials", resourceType: "Practice", level: "Intermediate", skillId: "skill_tf" },
    { title: "Linux Journey", url: "https://linuxjourney.com/", resourceType: "Course", level: "Beginner", skillId: "skill_linux" }
  ]
};
