const fs = require('fs');
const path = require('path');

const resourcesPath = path.join(__dirname, 'masterData', 'resources.ts');
let content = fs.readFileSync(resourcesPath, 'utf8');

const newResources = `
  "res_advanced_react_patterns": {
    id: "res_advanced_react_patterns",
    slug: "advanced-react-patterns",
    title: "Advanced React Patterns",
    description: "Learn advanced patterns for building scalable React applications.",
    provider: "FrontendMasters",
    url: "https://frontendmasters.com/courses/advanced-react-patterns/",
    sourceType: "external",
    resourceType: "course",
    language: "en",
    difficultyLevel: "advanced",
    estimatedDuration: "10 hours",
    isFree: false,
    isActive: true,
    qualityScore: 95,
    skillIds: ["skill_react"],
    careerPathIds: ["cp_frontend"],
    academicCategoryIds: ["ac_computer_science"],
    tags: ["react", "patterns", "frontend"],
    createdAt: now,
    updatedAt: now,
  },
  "res_docker_deep_dive": {
    id: "res_docker_deep_dive",
    slug: "docker-deep-dive",
    title: "Docker Deep Dive",
    description: "A comprehensive guide to Docker and containerization.",
    provider: "Pluralsight",
    url: "https://www.pluralsight.com/courses/docker-deep-dive",
    sourceType: "external",
    resourceType: "course",
    language: "en",
    difficultyLevel: "intermediate",
    estimatedDuration: "6 hours",
    isFree: false,
    isActive: true,
    qualityScore: 92,
    skillIds: ["skill_docker"],
    careerPathIds: ["cp_devops"],
    academicCategoryIds: ["ac_computer_science"],
    tags: ["docker", "devops", "containers"],
    createdAt: now,
    updatedAt: now,
  },
  "res_k8s_up_and_running": {
    id: "res_k8s_up_and_running",
    slug: "kubernetes-up-and-running",
    title: "Kubernetes Up and Running",
    description: "Dive into Kubernetes in production.",
    provider: "OReilly",
    sourceType: "external",
    resourceType: "book",
    language: "en",
    difficultyLevel: "advanced",
    estimatedDuration: "25 hours",
    isFree: false,
    isActive: true,
    qualityScore: 94,
    skillIds: ["skill_kubernetes"],
    careerPathIds: ["cp_devops"],
    academicCategoryIds: ["ac_computer_science"],
    tags: ["kubernetes", "devops", "orchestration"],
    createdAt: now,
    updatedAt: now,
  },
  "res_clean_code": {
    id: "res_clean_code",
    slug: "clean-code-book",
    title: "Clean Code",
    description: "A Handbook of Agile Software Craftsmanship.",
    provider: "Prentice Hall",
    sourceType: "external",
    resourceType: "book",
    language: "en",
    difficultyLevel: "intermediate",
    estimatedDuration: "30 hours",
    isFree: false,
    isActive: true,
    qualityScore: 99,
    skillIds: ["skill_python"],
    careerPathIds: ["cp_backend", "cp_frontend", "cp_fullstack"],
    academicCategoryIds: ["ac_software_engineering"],
    tags: ["clean-code", "best-practices", "engineering"],
    createdAt: now,
    updatedAt: now,
  },
  "res_aws_certified_solutions": {
    id: "res_aws_certified_solutions",
    slug: "aws-certified-solutions-architect",
    title: "AWS Certified Solutions Architect",
    description: "Study guide for the AWS CSA Associate exam.",
    provider: "ACloudGuru",
    url: "https://acloudguru.com/course/aws-certified-solutions-architect-associate",
    sourceType: "external",
    resourceType: "course",
    language: "en",
    difficultyLevel: "intermediate",
    estimatedDuration: "40 hours",
    isFree: false,
    isActive: true,
    qualityScore: 96,
    skillIds: ["skill_aws"],
    careerPathIds: ["cp_cloud"],
    academicCategoryIds: ["ac_computer_science"],
    tags: ["aws", "cloud", "certification"],
    createdAt: now,
    updatedAt: now,
  },
  "res_practical_ml": {
    id: "res_practical_ml",
    slug: "practical-machine-learning",
    title: "Practical Machine Learning",
    description: "Hands-on ML with Scikit-Learn, Keras, and TensorFlow.",
    provider: "OReilly",
    sourceType: "external",
    resourceType: "book",
    language: "en",
    difficultyLevel: "advanced",
    estimatedDuration: "50 hours",
    isFree: false,
    isActive: true,
    qualityScore: 98,
    skillIds: ["skill_machine_learning"],
    careerPathIds: ["cp_data_science", "cp_ai"],
    academicCategoryIds: ["ac_data_science"],
    tags: ["machine-learning", "ai", "book"],
    createdAt: now,
    updatedAt: now,
  },
  "res_system_design_primer": {
    id: "res_system_design_primer",
    slug: "system-design-primer",
    title: "System Design Primer",
    description: "Learn how to design large-scale systems.",
    provider: "GitHub",
    url: "https://github.com/donnemartin/system-design-primer",
    sourceType: "external",
    resourceType: "guide",
    language: "en",
    difficultyLevel: "advanced",
    estimatedDuration: "35 hours",
    isFree: true,
    isActive: true,
    qualityScore: 97,
    skillIds: ["skill_system_design", "skill_architecture"],
    careerPathIds: ["cp_backend", "cp_fullstack", "cp_cloud"],
    academicCategoryIds: ["ac_software_engineering"],
    tags: ["system-design", "architecture", "interview"],
    createdAt: now,
    updatedAt: now,
  }`;

content = content.replace(/};\s*$/, `,${newResources}\n};\n`);
fs.writeFileSync(resourcesPath, content, 'utf8');
console.log('Added 7 resources.');
