import { Category, ID } from "../../../src/types/database";

const now = new Date().toISOString();

export const academicCategories: Record<ID, Category> = {
  "cat_academic_cs": {
    id: "cat_academic_cs",
    slug: "computer-science",
    title: "Computer Science & IT",
    description: "Studies relating to algorithms, systems, networks, and computing.",
    sortOrder: 10,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_academic_math": {
    id: "cat_academic_math",
    slug: "mathematics-and-statistics",
    title: "Mathematics & Statistics",
    description: "Applied math, pure math, statistics, and probability.",
    sortOrder: 20,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_academic_engineering": {
    id: "cat_academic_engineering",
    slug: "engineering",
    title: "Engineering",
    description: "Mechanical, electrical, civil, and industrial engineering.",
    sortOrder: 30,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_academic_business": {
    id: "cat_academic_business",
    slug: "business-administration",
    title: "Business Administration",
    description: "Finance, accounting, management, and marketing studies.",
    sortOrder: 40,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_academic_design": {
    id: "cat_academic_design",
    slug: "design-and-arts",
    title: "Design & Arts",
    description: "Graphic design, fine arts, industrial design, and multimedia.",
    sortOrder: 50,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_academic_science": {
    id: "cat_academic_science",
    slug: "natural-sciences",
    title: "Natural Sciences",
    description: "Physics, chemistry, biology, and environmental sciences.",
    sortOrder: 60,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_academic_humanities": {
    id: "cat_academic_humanities",
    slug: "humanities-and-social-sciences",
    title: "Humanities & Social Sciences",
    description: "Psychology, sociology, history, literature, and philosophy.",
    sortOrder: 70,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_academic_medicine": {
    id: "cat_academic_medicine",
    slug: "medicine-and-health",
    title: "Medicine & Health",
    description: "Pre-med, nursing, public health, and biomedical sciences.",
    sortOrder: 80,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_academic_law": {
    id: "cat_academic_law",
    slug: "law-and-legal-studies",
    title: "Law & Legal Studies",
    description: "Corporate law, criminal justice, and international relations.",
    sortOrder: 90,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_academic_education": {
    id: "cat_academic_education",
    slug: "education",
    title: "Education",
    description: "Pedagogy, early childhood education, and special education.",
    sortOrder: 100,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  }
};
