import { CareerPath, ID } from "../../../src/types/database";

const now = new Date().toISOString();

export const careerPaths: Record<ID, CareerPath> = {
  "path_frontend_dev": {
    id: "path_frontend_dev",
    slug: "frontend-developer",
    title: "Frontend Developer",
    description: "Build user-facing interfaces and interactive web experiences.",
    longDescription: "Frontend developers are responsible for implementing visual elements that users see and interact with in a web application. They combine design, technology, and programming to code a website's appearance.",
    categoryId: "cat_career_tech",
    industryDomain: "Software Engineering",
    demandLevel: "high",
    requiredEducation: "Bachelor's degree or equivalent bootcamp experience",
    averagePreparationTime: "6-12 months",
    beginnerFriendly: true,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "path_backend_dev": {
    id: "path_backend_dev",
    slug: "backend-developer",
    title: "Backend Developer",
    description: "Architect the server-side logic, databases, and APIs of applications.",
    longDescription: "Backend developers focus on databases, backend logic, APIs, architecture, and servers. They ensure that websites perform correctly, focusing on behind-the-scenes activities that happen when performing any action on a website.",
    categoryId: "cat_career_tech",
    industryDomain: "Software Engineering",
    demandLevel: "very_high",
    requiredEducation: "Bachelor's degree in Computer Science",
    averagePreparationTime: "9-15 months",
    beginnerFriendly: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "path_fullstack_dev": {
    id: "path_fullstack_dev",
    slug: "full-stack-developer",
    title: "Full Stack Developer",
    description: "Master both frontend and backend development to build end-to-end solutions.",
    longDescription: "Full stack developers are versatile engineers capable of tackling both client and server software. They understand how everything works from top to bottom, making them invaluable for startups and complex enterprise projects.",
    categoryId: "cat_career_tech",
    industryDomain: "Software Engineering",
    demandLevel: "very_high",
    requiredEducation: "Bachelor's degree or extensive portfolio",
    averagePreparationTime: "12-18 months",
    beginnerFriendly: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "path_data_scientist": {
    id: "path_data_scientist",
    slug: "data-scientist",
    title: "Data Scientist",
    description: "Analyze complex data to extract actionable insights and build predictive models.",
    longDescription: "Data scientists utilize their analytical, statistical, and programming skills to collect, analyze, and interpret large data sets. They then use this information to develop data-driven solutions to difficult business challenges.",
    categoryId: "cat_career_data",
    industryDomain: "Data Analytics",
    demandLevel: "very_high",
    requiredEducation: "Master's degree preferred",
    averagePreparationTime: "12-24 months",
    beginnerFriendly: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "path_ui_ux_designer": {
    id: "path_ui_ux_designer",
    slug: "ui-ux-designer",
    title: "UI/UX Designer",
    description: "Design intuitive, engaging, and highly functional digital product experiences.",
    longDescription: "UI/UX designers are responsible for the overall feel of the product (UX) and how the product is laid out (UI). They work closely with product managers and engineers to realize a seamless product experience.",
    categoryId: "cat_career_design",
    industryDomain: "Design",
    demandLevel: "high",
    requiredEducation: "Bachelor's degree or strong design portfolio",
    averagePreparationTime: "6-12 months",
    beginnerFriendly: true,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "path_product_manager": {
    id: "path_product_manager",
    slug: "product-manager",
    title: "Product Manager",
    description: "Lead cross-functional teams to deliver products that meet customer needs.",
    longDescription: "Product Managers identify the customer need and the larger business objectives that a product or feature will fulfill, articulate what success looks like for a product, and rally a team to turn that vision into a reality.",
    categoryId: "cat_career_business",
    industryDomain: "Business Operations",
    demandLevel: "high",
    requiredEducation: "Bachelor's degree (Business or Tech)",
    averagePreparationTime: "12-24 months",
    beginnerFriendly: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "path_cloud_architect": {
    id: "path_cloud_architect",
    slug: "cloud-architect",
    title: "Cloud Architect",
    description: "Design, deploy, and manage scalable and secure cloud infrastructure.",
    longDescription: "Cloud Architects oversee a company's cloud computing strategy, including cloud adoption plans, cloud application design, and cloud management and monitoring. They possess deep knowledge of AWS, Azure, or GCP.",
    categoryId: "cat_career_tech",
    industryDomain: "Cloud Computing",
    demandLevel: "very_high",
    requiredEducation: "Bachelor's degree + Professional Certifications",
    averagePreparationTime: "24-36 months",
    beginnerFriendly: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "path_cybersec_analyst": {
    id: "path_cybersec_analyst",
    slug: "cybersecurity-analyst",
    title: "Cybersecurity Analyst",
    description: "Protect organizational data and infrastructure from cyber threats.",
    longDescription: "Cybersecurity analysts protect company hardware, software, and networks from cybercriminals. Their primary role is to understand company IT infrastructure in detail, monitor it at all times, and evaluate threats that could potentially breach the network.",
    categoryId: "cat_career_tech",
    industryDomain: "Information Security",
    demandLevel: "very_high",
    requiredEducation: "Bachelor's degree + Security Certifications",
    averagePreparationTime: "12-18 months",
    beginnerFriendly: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "path_digital_marketer": {
    id: "path_digital_marketer",
    slug: "digital-marketing-specialist",
    title: "Digital Marketing Specialist",
    description: "Drive brand awareness and lead generation through digital channels.",
    longDescription: "Digital marketers are responsible for using digital channels to generate leads and build brand awareness. They manage SEO, content marketing, social media strategies, and digital advertising campaigns.",
    categoryId: "cat_career_marketing",
    industryDomain: "Marketing",
    demandLevel: "medium",
    requiredEducation: "Bachelor's degree in Marketing or Communications",
    averagePreparationTime: "3-9 months",
    beginnerFriendly: true,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "path_ai_engineer": {
    id: "path_ai_engineer",
    slug: "ai-engineer",
    title: "AI Engineer",
    description: "Build, test, and deploy artificial intelligence and machine learning models.",
    longDescription: "AI engineers build AI models using machine learning algorithms and deep learning neural networks to draw business insights. They sit at the intersection of software engineering and data science.",
    categoryId: "cat_career_data",
    industryDomain: "Artificial Intelligence",
    demandLevel: "very_high",
    requiredEducation: "Master's degree in Computer Science or AI",
    averagePreparationTime: "18-36 months",
    beginnerFriendly: false,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  }
};
