export const getCareerPaths = (timestamp: string): Record<string, any> => {
  const paths = [
    {
      id: "path_frontend_developer",
      title: "Frontend Developer",
      slug: "frontend-developer",
      categoryId: "ccat_frontend",
      description: "Build user interfaces and client-side web applications.",
      longDescription: "Frontend Developers focus on what the user sees and interacts with in a web browser. They use HTML, CSS, JavaScript, and modern frameworks to create responsive, accessible, and fast web applications.",
      demandLevel: "High",
      industryDomain: "Technology",
      requiredEducation: "Self-taught / Bootcamp / Degree",
      averagePreparationTime: "3-6 months",
      beginnerFriendly: true,
      portfolioIdeas: ["Personal portfolio website", "E-commerce product page clone", "Weather dashboard using a public API"],
      commonTools: ["Figma", "Chrome DevTools", "Webpack/Vite", "npm/yarn"],
      responsibilities: ["Translating UI/UX design wireframes to code", "Optimizing applications for maximum speed", "Ensuring cross-browser compatibility"],
      roadmapSteps: ["Master HTML/CSS", "Deep dive into JavaScript", "Learn React or Vue", "Understand state management", "Learn CSS frameworks"]
    },
    {
      id: "path_backend_developer",
      title: "Backend Developer",
      slug: "backend-developer",
      categoryId: "ccat_backend",
      description: "Build APIs, manage databases, and handle server-side logic.",
      longDescription: "Backend Developers build the invisible engine that powers websites and apps. They focus on database management, API creation, and server architecture to ensure data flows securely and efficiently.",
      demandLevel: "High",
      industryDomain: "Technology",
      requiredEducation: "CS Degree preferred but not required",
      averagePreparationTime: "6-9 months",
      beginnerFriendly: false,
      portfolioIdeas: ["RESTful API for a blog", "User authentication system", "Real-time chat server using WebSockets"],
      commonTools: ["Postman", "Docker", "AWS/GCP", "Redis"],
      responsibilities: ["Database design and optimization", "Building robust APIs", "Implementing security and data protection", "Server scaling"],
      roadmapSteps: ["Learn a backend language", "Master relational databases", "Learn API design", "Understand caching", "Learn basic DevOps"]
    },
    {
      id: "path_fullstack_developer",
      title: "Full Stack Developer",
      slug: "full-stack-developer",
      categoryId: "ccat_fullstack",
      description: "Handle both frontend and backend development tasks.",
      longDescription: "Full Stack Developers are versatile engineers capable of working on all layers of an application, from configuring servers and databases to building user interfaces and everything in between.",
      demandLevel: "Very High",
      industryDomain: "Technology",
      requiredEducation: "Self-taught / Bootcamp / Degree",
      averagePreparationTime: "9-12 months",
      beginnerFriendly: false,
      portfolioIdeas: ["Full-stack task management app", "E-commerce platform with stripe integration", "Social media clone"],
      commonTools: ["VS Code", "Git", "Docker", "Figma"],
      responsibilities: ["End-to-end application development", "Designing system architectures", "Database schema design", "UI implementation"],
      roadmapSteps: ["Master Frontend basics", "Learn a Backend language", "Understand Databases", "Learn to deploy applications", "Master CI/CD basics"]
    },
    {
      id: "path_mobile_developer",
      title: "Mobile App Developer",
      slug: "mobile-app-developer",
      categoryId: "ccat_mobile",
      description: "Create applications for iOS and Android devices.",
      longDescription: "Mobile App Developers specialize in building native or cross-platform applications for smartphones and tablets. They work with frameworks like React Native, Flutter, Swift, or Kotlin.",
      demandLevel: "High",
      industryDomain: "Technology",
      requiredEducation: "Self-taught / Degree",
      averagePreparationTime: "6-9 months",
      beginnerFriendly: true,
      portfolioIdeas: ["To-do list app", "Weather app", "Fitness tracker app"],
      commonTools: ["Android Studio", "Xcode", "Firebase", "Figma"],
      responsibilities: ["Building mobile interfaces", "Integrating native device APIs", "Publishing apps to stores"],
      roadmapSteps: ["Learn Dart or Swift/Kotlin", "Master UI components", "Understand state management", "Learn local storage", "Publish an app"]
    },
    {
      id: "path_data_analyst",
      title: "Data Analyst",
      slug: "data-analyst",
      categoryId: "ccat_data",
      description: "Translate data into actionable business insights.",
      longDescription: "Data Analysts collect, process, and perform statistical analyses on large datasets. They discover how data can be used to answer questions and solve problems.",
      demandLevel: "High",
      industryDomain: "Cross-industry",
      requiredEducation: "Bachelor's Degree",
      averagePreparationTime: "4-8 months",
      beginnerFriendly: true,
      portfolioIdeas: ["Sales dashboard", "Customer segmentation analysis", "Marketing campaign ROI report"],
      commonTools: ["Excel", "Tableau/Power BI", "Jupyter", "SQL"],
      responsibilities: ["Data cleaning", "Creating dashboards", "Reporting insights to stakeholders"],
      roadmapSteps: ["Master Excel", "Learn SQL", "Learn Python/R", "Master a BI tool", "Build a data portfolio"]
    },
    {
      id: "path_data_scientist",
      title: "Data Scientist",
      slug: "data-scientist",
      categoryId: "ccat_data",
      description: "Analyze complex data to extract insights and build predictive models.",
      longDescription: "Data Scientists use statistics, machine learning, and programming to analyze large datasets, build predictive models, and solve complex business problems.",
      demandLevel: "Very High",
      industryDomain: "Cross-industry",
      requiredEducation: "Master's/PhD often preferred, Bachelor's minimum",
      averagePreparationTime: "12-18 months",
      beginnerFriendly: false,
      portfolioIdeas: ["Predictive model for housing prices", "Customer churn analysis", "Recommendation system"],
      commonTools: ["Jupyter", "Apache Spark", "Git", "TensorFlow/PyTorch"],
      responsibilities: ["Data preprocessing", "Building machine learning models", "Data storytelling", "Model deployment"],
      roadmapSteps: ["Learn Python and SQL", "Master Statistics", "Learn Pandas/NumPy", "Study Machine Learning algorithms", "Deploy ML models"]
    },
    {
      id: "path_ai_engineer",
      title: "AI Engineer",
      slug: "ai-engineer",
      categoryId: "ccat_ai",
      description: "Build, test, and deploy AI models and systems.",
      longDescription: "AI Engineers are responsible for developing, programming, and training the complex networks of algorithms that make up AI so that they can function like a human brain.",
      demandLevel: "Very High",
      industryDomain: "Technology",
      requiredEducation: "Master's/Degree in CS/Math",
      averagePreparationTime: "12-24 months",
      beginnerFriendly: false,
      portfolioIdeas: ["Chatbot using LLMs", "Image recognition tool", "Sentiment analysis API"],
      commonTools: ["PyTorch", "Hugging Face", "Docker", "AWS/GCP"],
      responsibilities: ["Training neural networks", "Optimizing model performance", "Integrating AI into applications"],
      roadmapSteps: ["Master Python", "Learn Deep Learning basics", "Understand NLP/Computer Vision", "Work with large language models", "Deploy AI endpoints"]
    },
    {
      id: "path_cybersecurity_analyst",
      title: "Cybersecurity Analyst",
      slug: "cybersecurity-analyst",
      categoryId: "ccat_cyber",
      description: "Protect systems and networks from digital attacks.",
      longDescription: "Cybersecurity Analysts monitor network traffic, identify vulnerabilities, and respond to security breaches to protect an organization's data and infrastructure.",
      demandLevel: "Very High",
      industryDomain: "Cross-industry",
      requiredEducation: "Bachelor's Degree + Certifications",
      averagePreparationTime: "6-12 months",
      beginnerFriendly: true,
      portfolioIdeas: ["Set up a home lab firewall", "Conduct a vulnerability scan report", "Analyze malware in a sandbox"],
      commonTools: ["Wireshark", "Kali Linux", "Splunk", "Nmap"],
      responsibilities: ["Monitoring network traffic", "Incident response", "Conducting security audits", "Updating security protocols"],
      roadmapSteps: ["Learn networking fundamentals", "Learn Linux administration", "Get Security+ certification", "Practice on HackTheBox", "Learn Python scripting"]
    },
    {
      id: "path_cloud_engineer",
      title: "Cloud Engineer",
      slug: "cloud-engineer",
      categoryId: "ccat_cloud",
      description: "Design, build, and maintain cloud infrastructure.",
      longDescription: "Cloud Engineers are IT professionals responsible for any technological duties associated with cloud computing, including design, planning, management, maintenance, and support.",
      demandLevel: "High",
      industryDomain: "Technology",
      requiredEducation: "Degree + Cloud Certifications",
      averagePreparationTime: "6-12 months",
      beginnerFriendly: false,
      portfolioIdeas: ["Deploy a scalable web app on AWS", "Set up a serverless API", "Automate infrastructure with Terraform"],
      commonTools: ["AWS/Azure/GCP", "Terraform", "Docker", "Linux"],
      responsibilities: ["Managing cloud environments", "Optimizing cloud costs", "Ensuring cloud security and compliance"],
      roadmapSteps: ["Master Linux and Networking", "Learn a major cloud provider", "Get a cloud certification", "Learn Infrastructure as Code", "Understand containers"]
    },
    {
      id: "path_devops_engineer",
      title: "DevOps Engineer",
      slug: "devops-engineer",
      categoryId: "ccat_cloud",
      description: "Bridge the gap between development and IT operations.",
      longDescription: "DevOps Engineers introduce processes, tools, and methodologies to balance needs throughout the software development life cycle, from coding and deployment, to maintenance and updates.",
      demandLevel: "Very High",
      industryDomain: "Technology",
      requiredEducation: "Degree + Experience",
      averagePreparationTime: "9-15 months",
      beginnerFriendly: false,
      portfolioIdeas: ["Build a CI/CD pipeline", "Set up Kubernetes cluster", "Automate server configuration"],
      commonTools: ["Jenkins/GitHub Actions", "Kubernetes", "Docker", "Ansible/Terraform"],
      responsibilities: ["Building CI/CD pipelines", "Automating infrastructure", "Monitoring system performance"],
      roadmapSteps: ["Learn Linux and Scripting", "Master Git and CI/CD", "Learn Cloud fundamentals", "Master Docker and Kubernetes", "Learn Infrastructure as Code"]
    },
    {
      id: "path_ui_ux_designer",
      title: "UI/UX Designer",
      slug: "ui-ux-designer",
      categoryId: "ccat_uiux",
      description: "Design user-friendly interfaces and experiences.",
      longDescription: "UI/UX Designers focus on the user experience and user interface of a product. They ensure that the product is intuitive, accessible, and visually appealing.",
      demandLevel: "High",
      industryDomain: "Technology/Design",
      requiredEducation: "Degree in Design/HCI or Bootcamp",
      averagePreparationTime: "6-12 months",
      beginnerFriendly: true,
      portfolioIdeas: ["Redesign a popular app", "Create a wireframe for a new product", "Conduct a user research study"],
      commonTools: ["Figma", "Sketch", "InVision", "Adobe XD"],
      responsibilities: ["User research", "Wireframing and prototyping", "Designing high-fidelity interfaces", "Usability testing"],
      roadmapSteps: ["Understand UX principles", "Master a design tool (Figma)", "Learn user research methods", "Build a design portfolio", "Learn basic HTML/CSS"]
    },
    {
      id: "path_qa_tester",
      title: "Software QA Tester",
      slug: "software-qa-tester",
      categoryId: "ccat_product",
      description: "Ensure software quality through manual and automated testing.",
      longDescription: "Quality Assurance (QA) Testers are responsible for testing software products for bugs, glitches, and other issues before they are released to the public.",
      demandLevel: "Medium",
      industryDomain: "Technology",
      requiredEducation: "Degree or relevant certification",
      averagePreparationTime: "3-6 months",
      beginnerFriendly: true,
      portfolioIdeas: ["Write test cases for a website", "Automate testing for a login form", "Create a bug report"],
      commonTools: ["Selenium", "Cypress", "Jira", "Postman"],
      responsibilities: ["Creating test plans", "Executing manual tests", "Writing automated test scripts", "Reporting bugs"],
      roadmapSteps: ["Learn software development lifecycle", "Understand manual testing", "Learn API testing", "Master an automation tool", "Learn continuous testing"]
    }
  ];

  const updates: Record<string, any> = {};
  
  paths.forEach(path => {
    updates[`public_content/career_paths/${path.id}`] = {
      ...path,
      isActive: true,
      createdAt: timestamp,
      updatedAt: timestamp
    };
  });

  return updates;
};
