import { Category, ID } from "../../../src/types/database";

const now = new Date().toISOString();

export const careerCategories: Record<ID, Category> = {
  "cat_career_tech": {
    id: "cat_career_tech",
    slug: "technology-and-software",
    title: "Technology & Software",
    description: "Careers involving software engineering, systems architecture, and application development.",
    sortOrder: 10,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_career_data": {
    id: "cat_career_data",
    slug: "data-and-ai",
    title: "Data & AI",
    description: "Careers focusing on data analysis, machine learning, and artificial intelligence.",
    sortOrder: 20,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_career_design": {
    id: "cat_career_design",
    slug: "design-and-creative",
    title: "Design & Creative",
    description: "Careers spanning UI/UX design, graphic arts, and creative direction.",
    sortOrder: 30,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_career_business": {
    id: "cat_career_business",
    slug: "business-operations",
    title: "Business & Operations",
    description: "Management, strategy, human resources, and corporate operations.",
    sortOrder: 40,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_career_marketing": {
    id: "cat_career_marketing",
    slug: "marketing-and-sales",
    title: "Marketing & Sales",
    description: "Digital marketing, brand management, sales, and public relations.",
    sortOrder: 50,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_career_finance": {
    id: "cat_career_finance",
    slug: "finance-and-accounting",
    title: "Finance & Accounting",
    description: "Careers in corporate finance, investment banking, and accounting.",
    sortOrder: 60,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_career_engineering": {
    id: "cat_career_engineering",
    slug: "traditional-engineering",
    title: "Traditional Engineering",
    description: "Mechanical, electrical, civil, and industrial engineering fields.",
    sortOrder: 70,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_career_healthcare": {
    id: "cat_career_healthcare",
    slug: "healthcare-and-medicine",
    title: "Healthcare & Medicine",
    description: "Careers related to medical practice, nursing, and healthcare administration.",
    sortOrder: 80,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_career_education": {
    id: "cat_career_education",
    slug: "education-and-training",
    title: "Education & Training",
    description: "Teaching, instructional design, and academic administration.",
    sortOrder: 90,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_career_security": {
    id: "cat_career_security",
    slug: "security-and-compliance",
    title: "Security & Compliance",
    description: "Cybersecurity, risk management, and legal compliance.",
    sortOrder: 100,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  }
};
