import { PracticeTask, Project, ID } from "../../../src/types/database";

const now = new Date().toISOString();

export const practiceTasks: Record<ID, PracticeTask> = {
  "task_js_functions": {
    id: "task_js_functions",
    title: "JavaScript Functions Practice",
    description: "Write 5 common utility functions.",
    instructions: "1. Write a function that reverses a string.\n2. Write a function that checks for a palindrome.\n3. Write a function to fetch API data.",
    skillIds: ["skill_javascript"],
    difficultyLevel: "beginner",
    estimatedTimeMinutes: 45,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "task_sql_queries": {
    id: "task_sql_queries",
    title: "SQL Data Extraction",
    description: "Write 3 complex SQL JOIN queries.",
    instructions: "Given a schema with Users and Orders, write queries to find the top 5 spenders, the average order value, and inactive users.",
    skillIds: ["skill_sql"],
    difficultyLevel: "intermediate",
    estimatedTimeMinutes: 60,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  }
,
  "task_auto_1": {
    id: "task_auto_1",
    title: "Generated Practice Task 1",
    description: "A professional practice task generated for MVP seeding.",
    instructions: "Complete the requirements outlined in the resources.",
    skillIds: ["skill_javascript", "skill_python"],
    difficultyLevel: "intermediate",
    estimatedTimeMinutes: 30 + 1 * 5,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "task_auto_2": {
    id: "task_auto_2",
    title: "Generated Practice Task 2",
    description: "A professional practice task generated for MVP seeding.",
    instructions: "Complete the requirements outlined in the resources.",
    skillIds: ["skill_javascript", "skill_python"],
    difficultyLevel: "intermediate",
    estimatedTimeMinutes: 30 + 2 * 5,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "task_auto_3": {
    id: "task_auto_3",
    title: "Generated Practice Task 3",
    description: "A professional practice task generated for MVP seeding.",
    instructions: "Complete the requirements outlined in the resources.",
    skillIds: ["skill_javascript", "skill_python"],
    difficultyLevel: "intermediate",
    estimatedTimeMinutes: 30 + 3 * 5,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "task_auto_4": {
    id: "task_auto_4",
    title: "Generated Practice Task 4",
    description: "A professional practice task generated for MVP seeding.",
    instructions: "Complete the requirements outlined in the resources.",
    skillIds: ["skill_javascript", "skill_python"],
    difficultyLevel: "intermediate",
    estimatedTimeMinutes: 30 + 4 * 5,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "task_auto_5": {
    id: "task_auto_5",
    title: "Generated Practice Task 5",
    description: "A professional practice task generated for MVP seeding.",
    instructions: "Complete the requirements outlined in the resources.",
    skillIds: ["skill_javascript", "skill_python"],
    difficultyLevel: "intermediate",
    estimatedTimeMinutes: 30 + 5 * 5,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "task_auto_6": {
    id: "task_auto_6",
    title: "Generated Practice Task 6",
    description: "A professional practice task generated for MVP seeding.",
    instructions: "Complete the requirements outlined in the resources.",
    skillIds: ["skill_javascript", "skill_python"],
    difficultyLevel: "intermediate",
    estimatedTimeMinutes: 30 + 6 * 5,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "task_auto_7": {
    id: "task_auto_7",
    title: "Generated Practice Task 7",
    description: "A professional practice task generated for MVP seeding.",
    instructions: "Complete the requirements outlined in the resources.",
    skillIds: ["skill_javascript", "skill_python"],
    difficultyLevel: "intermediate",
    estimatedTimeMinutes: 30 + 7 * 5,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "task_auto_8": {
    id: "task_auto_8",
    title: "Generated Practice Task 8",
    description: "A professional practice task generated for MVP seeding.",
    instructions: "Complete the requirements outlined in the resources.",
    skillIds: ["skill_javascript", "skill_python"],
    difficultyLevel: "intermediate",
    estimatedTimeMinutes: 30 + 8 * 5,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "task_auto_9": {
    id: "task_auto_9",
    title: "Generated Practice Task 9",
    description: "A professional practice task generated for MVP seeding.",
    instructions: "Complete the requirements outlined in the resources.",
    skillIds: ["skill_javascript", "skill_python"],
    difficultyLevel: "intermediate",
    estimatedTimeMinutes: 30 + 9 * 5,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "task_auto_10": {
    id: "task_auto_10",
    title: "Generated Practice Task 10",
    description: "A professional practice task generated for MVP seeding.",
    instructions: "Complete the requirements outlined in the resources.",
    skillIds: ["skill_javascript", "skill_python"],
    difficultyLevel: "intermediate",
    estimatedTimeMinutes: 30 + 10 * 5,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "task_auto_11": {
    id: "task_auto_11",
    title: "Generated Practice Task 11",
    description: "A professional practice task generated for MVP seeding.",
    instructions: "Complete the requirements outlined in the resources.",
    skillIds: ["skill_javascript", "skill_python"],
    difficultyLevel: "intermediate",
    estimatedTimeMinutes: 30 + 11 * 5,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "task_auto_12": {
    id: "task_auto_12",
    title: "Generated Practice Task 12",
    description: "A professional practice task generated for MVP seeding.",
    instructions: "Complete the requirements outlined in the resources.",
    skillIds: ["skill_javascript", "skill_python"],
    difficultyLevel: "intermediate",
    estimatedTimeMinutes: 30 + 12 * 5,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "task_auto_13": {
    id: "task_auto_13",
    title: "Generated Practice Task 13",
    description: "A professional practice task generated for MVP seeding.",
    instructions: "Complete the requirements outlined in the resources.",
    skillIds: ["skill_javascript", "skill_python"],
    difficultyLevel: "intermediate",
    estimatedTimeMinutes: 30 + 13 * 5,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  }
};

export const projects: Record<ID, Project> = {
  "proj_weather_app": {
    id: "proj_weather_app",
    title: "React Weather Application",
    description: "Build a responsive weather dashboard using a public weather API.",
    requirements: [
      "Use React or Next.js",
      "Fetch data from OpenWeatherMap or similar",
      "Display a 5-day forecast",
      "Include a search bar for cities",
      "Deploy to Vercel or Netlify"
    ],
    skillIds: ["skill_react", "skill_javascript", "skill_nextjs"],
    careerPathIds: ["path_frontend_dev", "path_fullstack_dev"],
    difficultyLevel: "intermediate",
    estimatedHours: 15,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "proj_data_pipeline": {
    id: "proj_data_pipeline",
    title: "Python Data Pipeline",
    description: "Build a Python script that extracts, transforms, and loads CSV data into a SQLite database.",
    requirements: [
      "Use Pandas for transformations",
      "Clean missing values",
      "Load into an SQLite database via SQLAlchemy",
      "Document the code"
    ],
    skillIds: ["skill_python", "skill_pandas", "skill_sql"],
    careerPathIds: ["path_data_scientist"],
    difficultyLevel: "intermediate",
    estimatedHours: 10,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  }
,
  "proj_auto_1": {
    id: "proj_auto_1",
    title: "Generated Project 1",
    description: "A comprehensive project for portfolio building.",
    requirements: ["Requirement 1", "Requirement 2", "Requirement 3"],
    skillIds: ["skill_react", "skill_nodejs"],
    careerPathIds: ["path_fullstack_dev"],
    difficultyLevel: "advanced",
    estimatedHours: 10 + 1,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "proj_auto_2": {
    id: "proj_auto_2",
    title: "Generated Project 2",
    description: "A comprehensive project for portfolio building.",
    requirements: ["Requirement 1", "Requirement 2", "Requirement 3"],
    skillIds: ["skill_react", "skill_nodejs"],
    careerPathIds: ["cp_fullstack"],
    difficultyLevel: "advanced",
    estimatedHours: 10 + 2,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "proj_auto_3": {
    id: "proj_auto_3",
    title: "Generated Project 3",
    description: "A comprehensive project for portfolio building.",
    requirements: ["Requirement 1", "Requirement 2", "Requirement 3"],
    skillIds: ["skill_react", "skill_nodejs"],
    careerPathIds: ["cp_fullstack"],
    difficultyLevel: "advanced",
    estimatedHours: 10 + 3,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "proj_auto_4": {
    id: "proj_auto_4",
    title: "Generated Project 4",
    description: "A comprehensive project for portfolio building.",
    requirements: ["Requirement 1", "Requirement 2", "Requirement 3"],
    skillIds: ["skill_react", "skill_nodejs"],
    careerPathIds: ["cp_fullstack"],
    difficultyLevel: "advanced",
    estimatedHours: 10 + 4,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "proj_auto_5": {
    id: "proj_auto_5",
    title: "Generated Project 5",
    description: "A comprehensive project for portfolio building.",
    requirements: ["Requirement 1", "Requirement 2", "Requirement 3"],
    skillIds: ["skill_react", "skill_nodejs"],
    careerPathIds: ["cp_fullstack"],
    difficultyLevel: "advanced",
    estimatedHours: 10 + 5,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "proj_auto_6": {
    id: "proj_auto_6",
    title: "Generated Project 6",
    description: "A comprehensive project for portfolio building.",
    requirements: ["Requirement 1", "Requirement 2", "Requirement 3"],
    skillIds: ["skill_react", "skill_nodejs"],
    careerPathIds: ["cp_fullstack"],
    difficultyLevel: "advanced",
    estimatedHours: 10 + 6,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "proj_auto_7": {
    id: "proj_auto_7",
    title: "Generated Project 7",
    description: "A comprehensive project for portfolio building.",
    requirements: ["Requirement 1", "Requirement 2", "Requirement 3"],
    skillIds: ["skill_react", "skill_nodejs"],
    careerPathIds: ["cp_fullstack"],
    difficultyLevel: "advanced",
    estimatedHours: 10 + 7,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "proj_auto_8": {
    id: "proj_auto_8",
    title: "Generated Project 8",
    description: "A comprehensive project for portfolio building.",
    requirements: ["Requirement 1", "Requirement 2", "Requirement 3"],
    skillIds: ["skill_react", "skill_nodejs"],
    careerPathIds: ["cp_fullstack"],
    difficultyLevel: "advanced",
    estimatedHours: 10 + 8,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  }
};
