import { Resource, ID } from "../../../src/types/database";

const now = new Date().toISOString();

export const resources: Record<ID, Resource> = {
  // Programming & Dev Resources
  "res_mdn_js": {
    id: "res_mdn_js",
    slug: "mdn-javascript-guide",
    title: "MDN JavaScript Guide",
    description: "The official Mozilla Developer Network guide to JavaScript.",
    provider: "Mozilla",
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
    sourceType: "external",
    resourceType: "documentation",
    language: "en",
    difficultyLevel: "all_levels",
    estimatedDuration: "20 hours",
    isFree: true,
    isActive: true,
    qualityScore: 98,
    skillIds: ["skill_javascript"],
    careerPathIds: ["path_frontend_dev", "path_fullstack_dev"],
    academicCategoryIds: ["cat_academic_cs"],
    tags: ["javascript", "docs", "web"],
    createdAt: now,
    updatedAt: now,
  },
  "res_react_docs": {
    id: "res_react_docs",
    slug: "react-official-documentation",
    title: "React Official Documentation",
    description: "Learn how to think in React and build user interfaces.",
    provider: "Meta",
    url: "https://react.dev/",
    sourceType: "external",
    resourceType: "documentation",
    language: "en",
    difficultyLevel: "intermediate",
    estimatedDuration: "15 hours",
    isFree: true,
    isActive: true,
    qualityScore: 99,
    skillIds: ["skill_react", "skill_javascript"],
    careerPathIds: ["path_frontend_dev", "path_fullstack_dev"],
    academicCategoryIds: ["cat_academic_cs"],
    tags: ["react", "frontend", "ui"],
    createdAt: now,
    updatedAt: now,
  },
  "res_nextjs_learn": {
    id: "res_nextjs_learn",
    slug: "learn-nextjs-course",
    title: "Learn Next.js Course",
    description: "The official interactive course for learning Next.js App Router.",
    provider: "Vercel",
    url: "https://nextjs.org/learn",
    sourceType: "external",
    resourceType: "course",
    language: "en",
    difficultyLevel: "intermediate",
    estimatedDuration: "8 hours",
    isFree: true,
    isActive: true,
    qualityScore: 97,
    skillIds: ["skill_nextjs", "skill_react"],
    careerPathIds: ["path_frontend_dev", "path_fullstack_dev"],
    academicCategoryIds: ["cat_academic_cs"],
    tags: ["nextjs", "ssr", "course"],
    createdAt: now,
    updatedAt: now,
  },
  "res_ts_handbook": {
    id: "res_ts_handbook",
    slug: "typescript-handbook",
    title: "The TypeScript Handbook",
    description: "The official guide to learning TypeScript from scratch.",
    provider: "Microsoft",
    url: "https://www.typescriptlang.org/docs/handbook/intro.html",
    sourceType: "external",
    resourceType: "documentation",
    language: "en",
    difficultyLevel: "intermediate",
    estimatedDuration: "12 hours",
    isFree: true,
    isActive: true,
    qualityScore: 96,
    skillIds: ["skill_typescript", "skill_javascript"],
    careerPathIds: ["path_frontend_dev", "path_backend_dev", "path_fullstack_dev"],
    academicCategoryIds: ["cat_academic_cs"],
    tags: ["typescript", "typing"],
    createdAt: now,
    updatedAt: now,
  },
  "res_python_crash": {
    id: "res_python_crash",
    slug: "python-crash-course",
    title: "Python Crash Course Basics",
    description: "A fast-paced introduction to Python programming.",
    provider: "Beacon",
    sourceType: "internal",
    resourceType: "course",
    language: "en",
    difficultyLevel: "beginner",
    estimatedDuration: "10 hours",
    isFree: true,
    isActive: true,
    qualityScore: 90,
    skillIds: ["skill_python"],
    careerPathIds: ["path_backend_dev", "path_data_scientist", "path_ai_engineer"],
    academicCategoryIds: ["cat_academic_cs", "cat_academic_science"],
    tags: ["python", "basics"],
    createdAt: now,
    updatedAt: now,
  },

  // Data & Analytics Resources
  "res_sql_bolt": {
    id: "res_sql_bolt",
    slug: "sqlbolt-interactive-lessons",
    title: "SQLBolt Interactive Lessons",
    description: "Learn SQL with simple, interactive exercises.",
    provider: "SQLBolt",
    url: "https://sqlbolt.com/",
    sourceType: "external",
    resourceType: "practice",
    language: "en",
    difficultyLevel: "beginner",
    estimatedDuration: "6 hours",
    isFree: true,
    isActive: true,
    qualityScore: 95,
    skillIds: ["skill_sql"],
    careerPathIds: ["path_backend_dev", "path_data_scientist"],
    academicCategoryIds: ["cat_academic_cs", "cat_academic_math"],
    tags: ["sql", "database", "practice"],
    createdAt: now,
    updatedAt: now,
  },
  "res_pandas_docs": {
    id: "res_pandas_docs",
    slug: "10-minutes-to-pandas",
    title: "10 Minutes to pandas",
    description: "A short introduction to pandas, geared mainly for new users.",
    provider: "PyData",
    url: "https://pandas.pydata.org/docs/user_guide/10min.html",
    sourceType: "external",
    resourceType: "guide",
    language: "en",
    difficultyLevel: "beginner",
    estimatedDuration: "2 hours",
    isFree: true,
    isActive: true,
    qualityScore: 92,
    skillIds: ["skill_pandas", "skill_python"],
    careerPathIds: ["path_data_scientist"],
    academicCategoryIds: ["cat_academic_math"],
    tags: ["pandas", "python", "data"],
    createdAt: now,
    updatedAt: now,
  },
  "res_ml_crash_course": {
    id: "res_ml_crash_course",
    slug: "google-ml-crash-course",
    title: "Google Machine Learning Crash Course",
    description: "A fast-paced, practical introduction to machine learning.",
    provider: "Google",
    url: "https://developers.google.com/machine-learning/crash-course",
    sourceType: "external",
    resourceType: "course",
    language: "en",
    difficultyLevel: "intermediate",
    estimatedDuration: "15 hours",
    isFree: true,
    isActive: true,
    qualityScore: 98,
    skillIds: ["skill_machine_learning", "skill_python"],
    careerPathIds: ["path_data_scientist", "path_ai_engineer"],
    academicCategoryIds: ["cat_academic_cs", "cat_academic_math"],
    tags: ["ml", "ai", "google"],
    createdAt: now,
    updatedAt: now,
  },
  "res_d3_gallery": {
    id: "res_d3_gallery",
    slug: "d3-js-gallery",
    title: "D3.js Visualization Gallery",
    description: "Examples of data visualization built with D3.js.",
    provider: "Observable",
    url: "https://observablehq.com/@d3/gallery",
    sourceType: "external",
    resourceType: "article",
    language: "en",
    difficultyLevel: "advanced",
    estimatedDuration: "5 hours",
    isFree: true,
    isActive: true,
    qualityScore: 94,
    skillIds: ["skill_data_visualization", "skill_javascript"],
    careerPathIds: ["path_data_scientist", "path_frontend_dev"],
    academicCategoryIds: ["cat_academic_cs"],
    tags: ["d3", "visualization", "data"],
    createdAt: now,
    updatedAt: now,
  },

  // Design Resources
  "res_figma_basics": {
    id: "res_figma_basics",
    slug: "figma-basics-course",
    title: "Figma Basics Course",
    description: "Learn the fundamentals of designing interfaces in Figma.",
    provider: "Beacon",
    sourceType: "internal",
    resourceType: "course",
    language: "en",
    difficultyLevel: "beginner",
    estimatedDuration: "8 hours",
    isFree: true,
    isActive: true,
    qualityScore: 93,
    skillIds: ["skill_figma", "skill_wireframing"],
    careerPathIds: ["path_ui_ux_designer"],
    academicCategoryIds: ["cat_academic_design"],
    tags: ["figma", "design", "ui"],
    createdAt: now,
    updatedAt: now,
  },
  "res_nngroup_research": {
    id: "res_nngroup_research",
    slug: "nngroup-ux-research",
    title: "UX Research Cheat Sheet",
    description: "An overview of UX research methods by Nielsen Norman Group.",
    provider: "NN/g",
    url: "https://www.nngroup.com/articles/ux-research-cheat-sheet/",
    sourceType: "external",
    resourceType: "guide",
    language: "en",
    difficultyLevel: "all_levels",
    estimatedDuration: "3 hours",
    isFree: true,
    isActive: true,
    qualityScore: 96,
    skillIds: ["skill_user_research"],
    careerPathIds: ["path_ui_ux_designer", "path_product_manager"],
    academicCategoryIds: ["cat_academic_design", "cat_academic_humanities"],
    tags: ["ux", "research"],
    createdAt: now,
    updatedAt: now,
  },
  "res_wireframing_guide": {
    id: "res_wireframing_guide",
    slug: "comprehensive-guide-wireframing",
    title: "Comprehensive Guide to Wireframing",
    description: "Learn how to map out screens and user flows.",
    provider: "Beacon",
    sourceType: "internal",
    resourceType: "guide",
    language: "en",
    difficultyLevel: "beginner",
    estimatedDuration: "4 hours",
    isFree: true,
    isActive: true,
    qualityScore: 88,
    skillIds: ["skill_wireframing"],
    careerPathIds: ["path_ui_ux_designer"],
    academicCategoryIds: ["cat_academic_design"],
    tags: ["wireframing", "planning"],
    createdAt: now,
    updatedAt: now,
  },

  // Cloud & DevOps Resources
  "res_git_book": {
    id: "res_git_book",
    slug: "pro-git-book",
    title: "Pro Git Book",
    description: "The entire Pro Git book, written by Scott Chacon and Ben Straub.",
    provider: "Git",
    url: "https://git-scm.com/book/en/v2",
    sourceType: "external",
    resourceType: "documentation",
    language: "en",
    difficultyLevel: "all_levels",
    estimatedDuration: "20 hours",
    isFree: true,
    isActive: true,
    qualityScore: 97,
    skillIds: ["skill_git"],
    careerPathIds: ["path_frontend_dev", "path_backend_dev", "path_fullstack_dev", "path_cloud_architect"],
    academicCategoryIds: ["cat_academic_cs"],
    tags: ["git", "version-control"],
    createdAt: now,
    updatedAt: now,
  },
  "res_docker_curriculum": {
    id: "res_docker_curriculum",
    slug: "docker-curriculum",
    title: "Docker Curriculum for Beginners",
    description: "A comprehensive tutorial on getting started with Docker.",
    provider: "Docker Curriculum",
    url: "https://docker-curriculum.com/",
    sourceType: "external",
    resourceType: "course",
    language: "en",
    difficultyLevel: "beginner",
    estimatedDuration: "10 hours",
    isFree: true,
    isActive: true,
    qualityScore: 95,
    skillIds: ["skill_docker"],
    careerPathIds: ["path_backend_dev", "path_cloud_architect", "path_fullstack_dev"],
    academicCategoryIds: ["cat_academic_cs"],
    tags: ["docker", "devops"],
    createdAt: now,
    updatedAt: now,
  },
  "res_aws_fundamentals": {
    id: "res_aws_fundamentals",
    slug: "aws-cloud-practitioner",
    title: "AWS Cloud Practitioner Essentials",
    description: "Official Amazon training for fundamental cloud concepts.",
    provider: "AWS",
    url: "https://aws.amazon.com/training/digital/aws-cloud-practitioner-essentials/",
    sourceType: "external",
    resourceType: "course",
    language: "en",
    difficultyLevel: "beginner",
    estimatedDuration: "6 hours",
    isFree: true,
    isActive: true,
    qualityScore: 96,
    skillIds: ["skill_aws"],
    careerPathIds: ["path_cloud_architect", "path_backend_dev"],
    academicCategoryIds: ["cat_academic_cs"],
    tags: ["aws", "cloud"],
    createdAt: now,
    updatedAt: now,
  },

  // Security Resources
  "res_owasp_top_10": {
    id: "res_owasp_top_10",
    slug: "owasp-top-10",
    title: "OWASP Top 10 Web Application Security Risks",
    description: "The standard awareness document for developers and web application security.",
    provider: "OWASP",
    url: "https://owasp.org/www-project-top-ten/",
    sourceType: "external",
    resourceType: "documentation",
    language: "en",
    difficultyLevel: "intermediate",
    estimatedDuration: "4 hours",
    isFree: true,
    isActive: true,
    qualityScore: 99,
    skillIds: ["skill_web_security"],
    careerPathIds: ["path_backend_dev", "path_fullstack_dev", "path_cybersec_analyst"],
    academicCategoryIds: ["cat_academic_cs"],
    tags: ["security", "owasp", "web"],
    createdAt: now,
    updatedAt: now,
  },
  "res_network_sec_intro": {
    id: "res_network_sec_intro",
    slug: "network-security-introduction",
    title: "Introduction to Network Security",
    description: "Basic principles of securing computer networks.",
    provider: "Beacon",
    sourceType: "internal",
    resourceType: "article",
    language: "en",
    difficultyLevel: "beginner",
    estimatedDuration: "3 hours",
    isFree: true,
    isActive: true,
    qualityScore: 85,
    skillIds: ["skill_network_security"],
    careerPathIds: ["path_cybersec_analyst", "path_cloud_architect"],
    academicCategoryIds: ["cat_academic_cs"],
    tags: ["networking", "security"],
    createdAt: now,
    updatedAt: now,
  },

  // Product & Business
  "res_agile_manifesto": {
    id: "res_agile_manifesto",
    slug: "agile-manifesto",
    title: "The Agile Manifesto",
    description: "The core values and principles of Agile software development.",
    provider: "Agile Alliance",
    url: "https://agilemanifesto.org/",
    sourceType: "external",
    resourceType: "article",
    language: "en",
    difficultyLevel: "all_levels",
    estimatedDuration: "1 hours",
    isFree: true,
    isActive: true,
    qualityScore: 94,
    skillIds: ["skill_agile"],
    careerPathIds: ["path_product_manager", "path_fullstack_dev"],
    academicCategoryIds: ["cat_academic_business", "cat_academic_cs"],
    tags: ["agile", "philosophy"],
    createdAt: now,
    updatedAt: now,
  },
  "res_pm_guide": {
    id: "res_pm_guide",
    slug: "product-management-guide",
    title: "The Ultimate Guide to Product Management",
    description: "A comprehensive internal guide covering the entire product lifecycle.",
    provider: "Beacon",
    sourceType: "internal",
    resourceType: "guide",
    language: "en",
    difficultyLevel: "intermediate",
    estimatedDuration: "12 hours",
    isFree: true,
    isActive: true,
    qualityScore: 90,
    skillIds: ["skill_product_strategy", "skill_project_management"],
    careerPathIds: ["path_product_manager"],
    academicCategoryIds: ["cat_academic_business"],
    tags: ["product", "management", "strategy"],
    createdAt: now,
    updatedAt: now,
  },

  // Soft Skills
  "res_effective_comm": {
    id: "res_effective_comm",
    slug: "effective-communication-in-workplace",
    title: "Effective Communication in the Workplace",
    description: "How to write clear emails, present ideas, and listen actively.",
    provider: "Beacon",
    sourceType: "internal",
    resourceType: "article",
    language: "en",
    difficultyLevel: "all_levels",
    estimatedDuration: "2 hours",
    isFree: true,
    isActive: true,
    qualityScore: 88,
    skillIds: ["skill_communication"],
    careerPathIds: ["path_product_manager", "path_ui_ux_designer", "path_digital_marketer"],
    academicCategoryIds: ["cat_academic_business", "cat_academic_humanities"],
    tags: ["soft-skills", "communication"],
    createdAt: now,
    updatedAt: now,
  },

  // Marketing
  "res_seo_starter": {
    id: "res_seo_starter",
    slug: "google-seo-starter-guide",
    title: "Google SEO Starter Guide",
    description: "Official documentation from Google on how search engines work and how to optimize sites.",
    provider: "Google",
    url: "https://developers.google.com/search/docs/fundamentals/seo-starter-guide",
    sourceType: "external",
    resourceType: "guide",
    language: "en",
    difficultyLevel: "beginner",
    estimatedDuration: "5 hours",
    isFree: true,
    isActive: true,
    qualityScore: 98,
    skillIds: ["skill_seo", "skill_content_marketing"],
    careerPathIds: ["path_digital_marketer"],
    academicCategoryIds: ["cat_academic_business"],
    tags: ["seo", "marketing", "google"],
    createdAt: now,
    updatedAt: now,
  },

  // AI & Advanced
  "res_prompt_engineering": {
    id: "res_prompt_engineering",
    slug: "openai-prompt-engineering",
    title: "OpenAI Prompt Engineering Guide",
    description: "Strategies and tactics for getting better results from large language models.",
    provider: "OpenAI",
    url: "https://platform.openai.com/docs/guides/prompt-engineering",
    sourceType: "external",
    resourceType: "guide",
    language: "en",
    difficultyLevel: "intermediate",
    estimatedDuration: "4 hours",
    isFree: true,
    isActive: true,
    qualityScore: 97,
    skillIds: ["skill_prompt_engineering"],
    careerPathIds: ["path_ai_engineer", "path_data_scientist", "path_fullstack_dev"],
    academicCategoryIds: ["cat_academic_cs"],
    tags: ["ai", "prompting", "openai"],
    createdAt: now,
    updatedAt: now,
  },
  "res_deep_learning_book": {
    id: "res_deep_learning_book",
    slug: "deep-learning-book",
    title: "Deep Learning (Adaptive Computation and Machine Learning series)",
    description: "The definitive textbook on deep learning by Ian Goodfellow, Yoshua Bengio, and Aaron Courville.",
    provider: "MIT Press",
    url: "https://www.deeplearningbook.org/",
    sourceType: "external",
    resourceType: "documentation",
    language: "en",
    difficultyLevel: "expert",
    estimatedDuration: "100 hours",
    isFree: true,
    isActive: true,
    qualityScore: 99,
    skillIds: ["skill_deep_learning", "skill_machine_learning"],
    careerPathIds: ["path_ai_engineer"],
    academicCategoryIds: ["cat_academic_cs", "cat_academic_math"],
    tags: ["deep-learning", "ai", "book"],
    createdAt: now,
    updatedAt: now,
  }
,
  "res_advanced_react_patterns": {
    id: "res_advanced_react_patterns",
    slug: "advanced-react-patterns",
    title: "Advanced React Patterns",
    description: "Learn advanced patterns for building scalable React applications.",
    provider: "FrontendMasters",
    url: "https://frontendmasters.com/courses/advanced-react-patterns/",
    sourceType: "external",
    resourceType: "course",
    language: "en",
    difficultyLevel: "advanced",
    estimatedDuration: "10 hours",
    isFree: false,
    isActive: true,
    qualityScore: 95,
    skillIds: ["skill_react"],
    careerPathIds: ["path_frontend_dev"],
    academicCategoryIds: ["cat_academic_cs"],
    tags: ["react", "patterns", "frontend"],
    createdAt: now,
    updatedAt: now,
  },
  "res_docker_deep_dive": {
    id: "res_docker_deep_dive",
    slug: "docker-deep-dive",
    title: "Docker Deep Dive",
    description: "A comprehensive guide to Docker and containerization.",
    provider: "Pluralsight",
    url: "https://www.pluralsight.com/courses/docker-deep-dive",
    sourceType: "external",
    resourceType: "course",
    language: "en",
    difficultyLevel: "intermediate",
    estimatedDuration: "6 hours",
    isFree: false,
    isActive: true,
    qualityScore: 92,
    skillIds: ["skill_docker"],
    careerPathIds: ["path_cloud_architect"],
    academicCategoryIds: ["cat_academic_cs"],
    tags: ["docker", "devops", "containers"],
    createdAt: now,
    updatedAt: now,
  },
  "res_k8s_up_and_running": {
    id: "res_k8s_up_and_running",
    slug: "kubernetes-up-and-running",
    title: "Kubernetes Up and Running",
    description: "Dive into Kubernetes in production.",
    provider: "OReilly",
    sourceType: "external",
    resourceType: "guide",
    language: "en",
    difficultyLevel: "advanced",
    estimatedDuration: "25 hours",
    isFree: false,
    isActive: true,
    qualityScore: 94,
    skillIds: ["skill_docker"],
    careerPathIds: ["path_cloud_architect"],
    academicCategoryIds: ["cat_academic_cs"],
    tags: ["kubernetes", "devops", "orchestration"],
    createdAt: now,
    updatedAt: now,
  },
  "res_clean_code": {
    id: "res_clean_code",
    slug: "clean-code-book",
    title: "Clean Code",
    description: "A Handbook of Agile Software Craftsmanship.",
    provider: "Prentice Hall",
    sourceType: "external",
    resourceType: "guide",
    language: "en",
    difficultyLevel: "intermediate",
    estimatedDuration: "30 hours",
    isFree: false,
    isActive: true,
    qualityScore: 99,
    skillIds: ["skill_python"],
    careerPathIds: ["path_backend_dev", "path_frontend_dev", "path_fullstack_dev"],
    academicCategoryIds: ["cat_academic_cs"],
    tags: ["clean-code", "best-practices", "engineering"],
    createdAt: now,
    updatedAt: now,
  },
  "res_aws_certified_solutions": {
    id: "res_aws_certified_solutions",
    slug: "aws-certified-solutions-architect",
    title: "AWS Certified Solutions Architect",
    description: "Study guide for the AWS CSA Associate exam.",
    provider: "ACloudGuru",
    url: "https://acloudguru.com/course/aws-certified-solutions-architect-associate",
    sourceType: "external",
    resourceType: "course",
    language: "en",
    difficultyLevel: "intermediate",
    estimatedDuration: "40 hours",
    isFree: false,
    isActive: true,
    qualityScore: 96,
    skillIds: ["skill_aws"],
    careerPathIds: ["path_cloud_architect"],
    academicCategoryIds: ["cat_academic_cs"],
    tags: ["aws", "cloud", "certification"],
    createdAt: now,
    updatedAt: now,
  },
  "res_practical_ml": {
    id: "res_practical_ml",
    slug: "practical-machine-learning",
    title: "Practical Machine Learning",
    description: "Hands-on ML with Scikit-Learn, Keras, and TensorFlow.",
    provider: "OReilly",
    sourceType: "external",
    resourceType: "guide",
    language: "en",
    difficultyLevel: "advanced",
    estimatedDuration: "50 hours",
    isFree: false,
    isActive: true,
    qualityScore: 98,
    skillIds: ["skill_machine_learning"],
    careerPathIds: ["path_data_scientist", "path_ai_engineer"],
    academicCategoryIds: ["cat_academic_math"],
    tags: ["machine-learning", "ai", "book"],
    createdAt: now,
    updatedAt: now,
  },
  "res_system_design_primer": {
    id: "res_system_design_primer",
    slug: "system-design-primer",
    title: "System Design Primer",
    description: "Learn how to design large-scale systems.",
    provider: "GitHub",
    url: "https://github.com/donnemartin/system-design-primer",
    sourceType: "external",
    resourceType: "guide",
    language: "en",
    difficultyLevel: "advanced",
    estimatedDuration: "35 hours",
    isFree: true,
    isActive: true,
    qualityScore: 97,
    skillIds: ["skill_python", "skill_python"],
    careerPathIds: ["path_backend_dev", "path_fullstack_dev", "path_cloud_architect"],
    academicCategoryIds: ["cat_academic_cs"],
    tags: ["system-design", "architecture", "interview"],
    createdAt: now,
    updatedAt: now,
  }
};
