import { Category, ID } from "../../../src/types/database";

const now = new Date().toISOString();

export const skillCategories: Record<ID, Category> = {
  "cat_skill_programming": {
    id: "cat_skill_programming",
    slug: "programming-and-development",
    title: "Programming & Development",
    description: "Core coding skills, languages, and software engineering principles.",
    sortOrder: 10,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_skill_data": {
    id: "cat_skill_data",
    slug: "data-and-analytics",
    title: "Data & Analytics",
    description: "Data science, machine learning, databases, and analytics.",
    sortOrder: 20,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_skill_design": {
    id: "cat_skill_design",
    slug: "design-and-ui-ux",
    title: "Design & UI/UX",
    description: "User experience, interface design, graphic design, and user research.",
    sortOrder: 30,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_skill_cloud": {
    id: "cat_skill_cloud",
    slug: "cloud-and-devops",
    title: "Cloud & DevOps",
    description: "Cloud infrastructure, continuous integration, and deployments.",
    sortOrder: 40,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_skill_security": {
    id: "cat_skill_security",
    slug: "cybersecurity",
    title: "Cybersecurity",
    description: "Information security, ethical hacking, and risk management.",
    sortOrder: 50,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_skill_product": {
    id: "cat_skill_product",
    slug: "product-management",
    title: "Product Management",
    description: "Product strategy, agile methodologies, and lifecycle management.",
    sortOrder: 60,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_skill_soft": {
    id: "cat_skill_soft",
    slug: "soft-skills",
    title: "Professional Soft Skills",
    description: "Communication, leadership, time management, and teamwork.",
    sortOrder: 70,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_skill_business": {
    id: "cat_skill_business",
    slug: "business-and-finance",
    title: "Business & Finance",
    description: "Corporate finance, business strategy, and operations.",
    sortOrder: 80,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_skill_marketing": {
    id: "cat_skill_marketing",
    slug: "digital-marketing",
    title: "Digital Marketing",
    description: "SEO, content marketing, growth hacking, and social media strategy.",
    sortOrder: 90,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  "cat_skill_ai": {
    id: "cat_skill_ai",
    slug: "artificial-intelligence",
    title: "Artificial Intelligence",
    description: "Deep learning, NLP, generative models, and neural networks.",
    sortOrder: 100,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  }
};
